sudo: false

language: java

node_js:
  - "6.9"

jdk:
 - oraclejdk8

before_install:
 - chmod +x test/run.sh
 - chmod +x test/after_success.sh

before_script:
  - npm install -g @angular/cli
 
script:
 - test/run.sh

after_success: 
 - test/after_success.sh
