sudo: false

language: java

jdk:
 - oraclejdk8

before_install:
 - chmod +x test/run.sh
 - chmod +x test/after_success.sh
 
install:
 - npm install -g angular-cli
 
script:
 - test/run.sh

after_success: 
 - test/after_success.sh
